SRC_PATH=/home/rippled/NewCoin

FILES = \
    ${SRC_PATH}/build/proto/ripple.pb.o \
    ${SRC_PATH}/build/obj/ripple/ParameterTable.o \
    ${SRC_PATH}/build/obj/ripple/ParseSection.o \
    ${SRC_PATH}/build/obj/ripple/Suppression.o \
    ${SRC_PATH}/build/obj/ripple/RippleCalc.o \
    ${SRC_PATH}/build/obj/ripple/HttpsClient.o \
    ${SRC_PATH}/build/obj/ripple/TransactionMeta.o \
    ${SRC_PATH}/build/obj/ripple/NicknameState.o \
    ${SRC_PATH}/build/obj/ripple/Serializer.o \
    ${SRC_PATH}/build/obj/ripple/RPCServer.o \
    ${SRC_PATH}/build/obj/ripple/rpc.o \
    ${SRC_PATH}/build/obj/ripple/SHAMapSync.o \
    ${SRC_PATH}/build/obj/ripple/AccountItems.o \
    ${SRC_PATH}/build/obj/ripple/OrderBook.o \
    ${SRC_PATH}/build/obj/ripple/AcceptedLedger.o \
    ${SRC_PATH}/build/obj/ripple/RangeSet.o \
    ${SRC_PATH}/build/obj/ripple/LedgerMaster.o \
    ${SRC_PATH}/build/obj/ripple/utils.o \
    ${SRC_PATH}/build/obj/ripple/Offer.o \
    ${SRC_PATH}/build/obj/ripple/SHAMapDiff.o \
    ${SRC_PATH}/build/obj/ripple/RegularKeySetTransactor.o \
    ${SRC_PATH}/build/obj/ripple/SerializedTransaction.o \
    ${SRC_PATH}/build/obj/ripple/OfferCreateTransactor.o \
    ${SRC_PATH}/build/obj/ripple/OrderBookDB.o \
    ${SRC_PATH}/build/obj/ripple/ECIES.o \
    ${SRC_PATH}/build/obj/ripple/UniqueNodeList.o \
    ${SRC_PATH}/build/obj/ripple/AmountRound.o \
    ${SRC_PATH}/build/obj/ripple/SHAMapNodes.o \
    ${SRC_PATH}/build/obj/ripple/WSDoor.o \
    ${SRC_PATH}/build/obj/ripple/LedgerFormats.o \
    ${SRC_PATH}/build/obj/ripple/TransactionQueue.o \
    ${SRC_PATH}/build/obj/ripple/Config.o \
    ${SRC_PATH}/build/obj/ripple/Amount.o \
    ${SRC_PATH}/build/obj/ripple/RippleState.o \
    ${SRC_PATH}/build/obj/ripple/SNTPClient.o \
    ${SRC_PATH}/build/obj/ripple/HTTPRequest.o \
    ${SRC_PATH}/build/obj/ripple/RPCErr.o \
    ${SRC_PATH}/build/obj/ripple/CallRPC.o \
    ${SRC_PATH}/build/obj/ripple/SerializedValidation.o \
    ${SRC_PATH}/build/obj/ripple/UpdateTables.o \
    ${SRC_PATH}/build/obj/ripple/DeterministicKeys.o \
    ${SRC_PATH}/build/obj/ripple/FeatureTable.o \
    ${SRC_PATH}/build/obj/ripple/Application.o \
    ${SRC_PATH}/build/obj/ripple/AccountSetTransactor.o \
    ${SRC_PATH}/build/obj/ripple/SerializedObject.o \
    ${SRC_PATH}/build/obj/ripple/Contract.o \
    ${SRC_PATH}/build/obj/ripple/LedgerTiming.o \
    ${SRC_PATH}/build/obj/ripple/InstanceCounter.o \
    ${SRC_PATH}/build/obj/ripple/TrustSetTransactor.o \
    ${SRC_PATH}/build/obj/ripple/Interpreter.o \
    ${SRC_PATH}/build/obj/ripple/Wallet.o \
    ${SRC_PATH}/build/obj/ripple/Ledger.o \
    ${SRC_PATH}/build/obj/ripple/JobQueue.o \
    ${SRC_PATH}/build/obj/ripple/PackedMessage.o \
    ${SRC_PATH}/build/obj/ripple/SerializedLedger.o \
    ${SRC_PATH}/build/obj/ripple/Pathfinder.o \
    ${SRC_PATH}/build/obj/ripple/RippleAddress.o \
    ${SRC_PATH}/build/obj/ripple/AccountState.o \
    ${SRC_PATH}/build/obj/ripple/Peer.o \
    ${SRC_PATH}/build/obj/ripple/SHAMap.o \
    ${SRC_PATH}/build/obj/ripple/TransactionMaster.o \
    ${SRC_PATH}/build/obj/ripple/LedgerAcquire.o \
    ${SRC_PATH}/build/obj/ripple/Operation.o \
    ${SRC_PATH}/build/obj/ripple/PaymentTransactor.o \
    ${SRC_PATH}/build/obj/ripple/PeerDoor.o \
    ${SRC_PATH}/build/obj/ripple/LedgerEntrySet.o \
    ${SRC_PATH}/build/obj/ripple/rfc1751.o \
    ${SRC_PATH}/build/obj/ripple/CanonicalTXSet.o \
    ${SRC_PATH}/build/obj/ripple/LedgerHistory.o \
    ${SRC_PATH}/build/obj/ripple/RPCSub.o \
    ${SRC_PATH}/build/obj/ripple/Transaction.o \
    ${SRC_PATH}/build/obj/ripple/ProofOfWork.o \
    ${SRC_PATH}/build/obj/ripple/ValidationCollection.o \
    ${SRC_PATH}/build/obj/ripple/TransactionErr.o \
    ${SRC_PATH}/build/obj/ripple/OfferCancelTransactor.o \
    ${SRC_PATH}/build/obj/ripple/WalletAddTransactor.o \
    ${SRC_PATH}/build/obj/ripple/ScriptData.o \
    ${SRC_PATH}/build/obj/ripple/TransactionFormats.o \
    ${SRC_PATH}/build/obj/ripple/Transactor.o \
    ${SRC_PATH}/build/obj/ripple/RPCHandler.o \
    ${SRC_PATH}/build/obj/ripple/Log.o \
    ${SRC_PATH}/build/obj/ripple/SerializedTypes.o \
    ${SRC_PATH}/build/obj/ripple/ConnectionPool.o \
    ${SRC_PATH}/build/obj/ripple/TransactionCheck.o \
    ${SRC_PATH}/build/obj/ripple/LoadManager.o \
    ${SRC_PATH}/build/obj/ripple/HashedObject.o \
    ${SRC_PATH}/build/obj/ripple/PlatRand.o \
    ${SRC_PATH}/build/obj/ripple/TransactionAcquire.o \
    ${SRC_PATH}/build/obj/ripple/NetworkOPs.o \
    ${SRC_PATH}/build/obj/ripple/LedgerProposal.o \
    ${SRC_PATH}/build/obj/ripple/LedgerConsensus.o \
    ${SRC_PATH}/build/obj/ripple/LoadMonitor.o \
    ${SRC_PATH}/build/obj/ripple/TransactionEngine.o \
    ${SRC_PATH}/build/obj/ripple/DBInit.o \
    ${SRC_PATH}/build/obj/ripple/RPCDoor.o \
    ${SRC_PATH}/build/obj/ripple/BitcoinUtil.o \
    ${SRC_PATH}/build/obj/ripple/FieldNames.o \
    ${SRC_PATH}/build/obj/database/sqlite3.o \
    ${SRC_PATH}/build/obj/database/SqliteDatabase.o \
    ${SRC_PATH}/build/obj/database/database.o \
    ${SRC_PATH}/build/obj/json/json_value.o \
    ${SRC_PATH}/build/obj/json/json_reader.o \
    ${SRC_PATH}/build/obj/json/json_writer.o \
    ${SRC_PATH}/build/obj/websocketpp/src/base64/base64.o \
    ${SRC_PATH}/build/obj/websocketpp/src/md5/md5.o \
    ${SRC_PATH}/build/obj/websocketpp/src/messages/data.o \
    ${SRC_PATH}/build/obj/websocketpp/src/network_utilities.o \
    ${SRC_PATH}/build/obj/websocketpp/src/processors/hybi_header.o \
    ${SRC_PATH}/build/obj/websocketpp/src/processors/hybi_util.o \
    ${SRC_PATH}/build/obj/websocketpp/src/sha1/sha1.o \
    ${SRC_PATH}/build/obj/websocketpp/src/uri.o

LIBS = \
    -pthread \
    -rdynamic \
    -lssl \
    -lcrypto \
    -lboost_date_time \
    -lboost_filesystem \
    -lboost_program_options \
    -lboost_regex \
    -lboost_system \
    -lboost_thread \
    -ldl \
    -lprotobuf \
    -lz

ripplegen:
	g++ -o ripplegen ripplegen.cpp \
	-I$(SRC_PATH)/src/cpp/ripple \
	-I$(SRC_PATH)/build/proto \
	$(FILES) $(LIBS) -Wall -O3
